/**
 * Emoji utility to map common names to Unicode characters
 * Extended for Mattermost-compatible autocomplete
 */

// Extended emoji map with categories for better organization
export const emojiMap: Record<string, string> = {
    // Smileys & Emotion
    'smile': '😄',
    'smiley': '😃',
    'grinning': '😀',
    'blush': '😊',
    'wink': '😉',
    'heart_eyes': '😍',
    'kissing_heart': '😘',
    'kissing': '😗',
    'kissing_smiling_eyes': '😙',
    'kissing_closed_eyes': '😚',
    'laughing': '😆',
    'satisfied': '😆',
    'grin': '😁',
    'joy': '😂',
    'rofl': '🤣',
    'relaxed': '☺️',
    'sweat_smile': '😅',
    'innocent': '😇',
    'slightly_smiling_face': '🙂',
    'upside_down_face': '🙃',
    'wink2': '😜',
    'relieved': '😌',
    'heart_eyes_cat': '😻',
    'smirk': '😏',
    'unamused': '😒',
    'sweat': '😓',
    'pensive': '😔',
    'confused': '😕',
    'confounded': '😖',
    'kissing_cat': '😽',
    'yum': '😋',
    'stuck_out_tongue': '😛',
    'stuck_out_tongue_winking_eye': '😜',
    'stuck_out_tongue_closed_eyes': '😝',
    'money_mouth_face': '🤑',
    'nerd_face': '🤓',
    'sunglasses': '😎',
    'hugging_face': '🤗',
    'smirk_cat': '😼',
    'scream_cat': '🙀',
    'crying_cat_face': '😿',
    'pouting_cat': '😾',
    
    // Emotion
    'smiling_face_with_hearts': '🥰',
    'star_struck': '🤩',
    'face_blowing_a_kiss': '😘',
    'face_savoring_food': '😋',
    'face_with_tongue': '😛',
    'zany_face': '🤪',
    'face_with_hand_over_mouth': '🤭',
    'shushing_face': '🤫',
    'thinking_face': '🤔',
    'thinking': '🤔',
    'zipper_mouth_face': '🤐',
    'face_with_raised_eyebrow': '🤨',
    'neutral_face': '😐',
    'expressionless': '😑',
    'no_mouth': '😶',
    'face_in_clouds': '😶‍🌫️',
    'smirking_face': '😏',
    'unamused_face': '😒',
    'face_with_rolling_eyes': '🙄',
    'grimacing': '😬',
    'face_exhaling': '😮‍💨',
    'lying_face': '🤥',
    'relieved_face': '😌',
    'pensive_face': '😔',
    'sleepy': '😪',
    'drooling_face': '🤤',
    'sleeping': '😴',
    'face_with_medical_mask': '😷',
    'face_with_thermometer': '🤒',
    'face_with_head_bandage': '🤕',
    'nauseated_face': '🤢',
    'face_vomiting': '🤮',
    'sneezing_face': '🤧',
    'hot_face': '🥵',
    'cold_face': '🥶',
    'woozy_face': '🥴',
    'dizzy_face': '😵',
    'face_with_spiral_eyes': '😵‍💫',
    'exploding_head': '🤯',
    'cowboy_hat_face': '🤠',
    'partying_face': '🥳',
    'disguised_face': '🥸',
    'ghost': '👻',
    'skull': '💀',
    'skull_and_crossbones': '☠️',
    
    // Hand gestures
    'wave': '👋',
    'raised_back_of_hand': '🤚',
    'raised_hand_with_fingers_splayed': '🖐️',
    'vulcan_salute': '🖖',
    'ok_hand': '👌',
    'pinched_fingers': '🤌',
    'pinching_hand': '🤏',
    'v': '✌️',
    'crossed_fingers': '🤞',
    'love_you_gesture': '🤟',
    'metal': '🤘',
    'call_me_hand': '🤙',
    'point_left': '👈',
    'point_right': '👉',
    'point_up_2': '👆',
    'middle_finger': '🖕',
    'fu': '🖕',
    'point_down': '👇',
    'point_up': '☝️',
    '+1': '👍',
    'thumbsup': '👍',
    '-1': '👎',
    'thumbsdown': '👎',
    'fist_raised': '✊',
    'fist': '✊',
    'facepunch': '👊',
    'punch': '👊',
    'left_facing_fist': '🤛',
    'right_facing_fist': '🤜',
    'clap': '👏',
    'raised_hands': '🙌',
    'open_hands': '👐',
    'palms_up_together': '🤲',
    'handshake': '🤝',
    'pray': '🙏',
    'writing_hand': '✍️',
    'nail_care': '💅',
    'selfie': '🤳',
    'muscle': '💪',
    'mechanical_arm': '🦾',
    'mechanical_leg': '🦿',
    'leg': '🦵',
    'foot': '🦶',
    'ear': '👂',
    'nose': '👃',
    'brain': '🧠',
    'anatomical_heart': '🫀',
    'lungs': '🫁',
    'tooth': '🦷',
    'bone': '🦴',
    'eyes': '👀',
    'eye': '👁️',
    'tongue': '👅',
    'lips': '👄',
    
    // Hearts
    'heart': '❤️',
    'heavy_heart_exclamation': '❣️',
    'broken_heart': '💔',
    'two_hearts': '💕',
    'sparkling_heart': '💖',
    'heartpulse': '💗',
    'growing_heart': '💗',
    'cupid': '💘',
    'blue_heart': '💙',
    'green_heart': '💚',
    'yellow_heart': '💛',
    'purple_heart': '💜',
    'brown_heart': '🤎',
    'black_heart': '🖤',
    'white_heart': '🤍',
    'heart_on_fire': '❤️‍🔥',
    'mending_heart': '❤️‍🩹',
    '100': '💯',
    'anger': '💢',
    'boom': '💥',
    'collision': '💥',
    'dizzy': '💫',
    'sweat_drops': '💦',
    'dash': '💨',
    'hole': '🕳️',
    'bomb': '💣',
    'speech_balloon': '💬',
    'eye_speech_bubble': '👁️‍🗨️',
    'left_speech_bubble': '🗨️',
    'right_anger_bubble': '🗯️',
    'thought_balloon': '💭',
    'zzz': '💤',
    
    // Nature
    'dog': '🐶',
    'cat': '🐱',
    'mouse': '🐭',
    'hamster': '🐹',
    'rabbit': '🐰',
    'fox_face': '🦊',
    'bear': '🐻',
    'panda_face': '🐼',
    'koala': '🐨',
    'tiger': '🐯',
    'lion': '🦁',
    'cow': '🐮',
    'pig': '🐷',
    'frog': '🐸',
    'monkey_face': '🐵',
    'see_no_evil': '🙈',
    'hear_no_evil': '🙉',
    'speak_no_evil': '🙊',
    'monkey': '🐒',
    'chicken': '🐔',
    'penguin': '🐧',
    'bird': '🐦',
    'baby_chick': '🐤',
    'hatching_chick': '🐣',
    'hatched_chick': '🐥',
    'duck': '🦆',
    'eagle': '🦅',
    'owl': '🦉',
    'bat': '🦇',
    'wolf': '🐺',
    'boar': '🐗',
    'horse': '🐴',
    'unicorn': '🦄',
    'bee': '🐝',
    'honeybee': '🐝',
    'bug': '🐛',
    'butterfly': '🦋',
    'snail': '🐌',
    'worm': '🪱',
    'lady_beetle': '🐞',
    'ant': '🐜',
    'mosquito': '🦟',
    'cricket': '🦗',
    'spider': '🕷️',
    'spider_web': '🕸️',
    'scorpion': '🦂',
    'turtle': '🐢',
    'snake': '🐍',
    'lizard': '🦎',
    't_rex': '🦖',
    'sauropod': '🦕',
    'octopus': '🐙',
    'squid': '🦑',
    'shrimp': '🦐',
    'lobster': '🦞',
    'crab': '🦀',
    'blowfish': '🐡',
    'tropical_fish': '🐠',
    'fish': '🐟',
    'dolphin': '🐬',
    'whale': '🐳',
    'whale2': '🐋',
    'shark': '🦈',
    'crocodile': '🐊',
    'tiger2': '🐅',
    'leopard': '🐆',
    'zebra': '🦓',
    'gorilla': '🦍',
    'orangutan': '🦧',
    'elephant': '🐘',
    'mammoth': '🦣',
    'bison': '🦬',
    'hippopotamus': '🦛',
    'rhinoceros': '🦏',
    'dromedary_camel': '🐪',
    'camel': '🐫',
    'giraffe': '🦒',
    'kangaroo': '🦘',
    'water_buffalo': '🐃',
    'ox': '🐂',
    'cow2': '🐄',
    'racehorse': '🐎',
    'pig2': '🐖',
    'ram': '🐏',
    'sheep': '🐑',
    'llama': '🦙',
    'goat': '🐐',
    'deer': '🦌',
    'dog2': '🐕',
    'poodle': '🐩',
    'guide_dog': '🦮',
    'service_dog': '🐕‍🦺',
    'cat2': '🐈',
    'black_cat': '🐈‍⬛',
    'rooster': '🐓',
    'turkey': '🦃',
    'dodo': '🦤',
    'peacock': '🦚',
    'parrot': '🦜',
    'swan': '🦢',
    'flamingo': '🦩',
    'dove': '🕊️',
    'rabbit2': '🐇',
    'raccoon': '🦝',
    'skunk': '🦨',
    'badger': '🦡',
    'beaver': '🦫',
    'otter': '🦦',
    'sloth': '🦥',
    'mouse2': '🐁',
    'rat': '🐀',
    'chipmunk': '🐿️',
    'hedgehog': '🦔',
    'feet': '🐾',
    'paw_prints': '🐾',
    'dragon': '🐉',
    'dragon_face': '🐲',
    'cactus': '🌵',
    'christmas_tree': '🎄',
    'evergreen_tree': '🌲',
    'deciduous_tree': '🌳',
    'palm_tree': '🌴',
    'seedling': '🌱',
    'herb': '🌿',
    'shamrock': '☘️',
    'four_leaf_clover': '🍀',
    'bamboo': '🎍',
    'tanabata_tree': '🎋',
    'leaves': '🍃',
    'fallen_leaf': '🍂',
    'maple_leaf': '🍁',
    'ear_of_rice': '🌾',
    'hibiscus': '🌺',
    'sunflower': '🌻',
    'rose': '🌹',
    'wilted_flower': '🥀',
    'tulip': '🌷',
    'blossom': '🌼',
    'cherry_blossom': '🌸',
    'white_flower': '💮',
    'lotus': '🪷',
    'bouquet': '💐',
    'mushroom': '🍄',
    
    // Food & Drink
    'grapes': '🍇',
    'melon': '🍈',
    'watermelon': '🍉',
    'tangerine': '🍊',
    'orange': '🍊',
    'mandarin': '🍊',
    'lemon': '🍋',
    'banana': '🍌',
    'pineapple': '🍍',
    'mango': '🥭',
    'apple': '🍎',
    'green_apple': '🍏',
    'pear': '🍐',
    'peach': '🍑',
    'cherries': '🍒',
    'strawberry': '🍓',
    'blueberries': '🫐',
    'kiwi_fruit': '🥝',
    'tomato': '🍅',
    'olive': '🫒',
    'coconut': '🥥',
    'avocado': '🥑',
    'eggplant': '🍆',
    'potato': '🥔',
    'carrot': '🥕',
    'corn': '🌽',
    'hot_pepper': '🌶️',
    'bell_pepper': '🫑',
    'cucumber': '🥒',
    'leafy_green': '🥬',
    'broccoli': '🥦',
    'garlic': '🧄',
    'onion': '🧅',
    'mushroom2': '🍄',
    'peanuts': '🥜',
    'chestnut': '🌰',
    'bread': '🍞',
    'croissant': '🥐',
    'baguette_bread': '🥖',
    'flatbread': '🫓',
    'pretzel': '🥨',
    'bagel': '🥯',
    'pancakes': '🥞',
    'waffle': '🧇',
    'cheese': '🧀',
    'meat_on_bone': '🍖',
    'poultry_leg': '🍗',
    'cut_of_meat': '🥩',
    'bacon': '🥓',
    'hamburger': '🍔',
    'fries': '🍟',
    'pizza': '🍕',
    'hotdog': '🌭',
    'sandwich': '🥪',
    'taco': '🌮',
    'burrito': '🌯',
    'tamale': '🫔',
    'stuffed_flatbread': '🥙',
    'falafel': '🧆',
    'egg': '🥚',
    'fried_egg': '🍳',
    'shallow_pan_of_food': '🥘',
    'stew': '🍲',
    'fondue': '🫕',
    'bowl_with_spoon': '🥣',
    'green_salad': '🥗',
    'popcorn': '🍿',
    'butter': '🧈',
    'salt': '🧂',
    'canned_food': '🥫',
    'bento': '🍱',
    'rice_cracker': '🍘',
    'rice_ball': '🍙',
    'rice': '🍚',
    'curry': '🍛',
    'ramen': '🍜',
    'spaghetti': '🍝',
    'sweet_potato': '🍠',
    'oden': '🍢',
    'sushi': '🍣',
    'fried_shrimp': '🍤',
    'fish_cake': '🍥',
    'moon_cake': '🥮',
    'dango': '🍡',
    'dumpling': '🥟',
    'fortune_cookie': '🥠',
    'takeout_box': '🥡',
    'squid2': '🦑',
    'oyster': '🦪',
    'icecream': '🍦',
    'shaved_ice': '🍧',
    'ice_cream': '🍨',
    'doughnut': '🍩',
    'cookie': '🍪',
    'birthday': '🎂',
    'cake': '🍰',
    'cupcake': '🧁',
    'pie': '🥧',
    'chocolate_bar': '🍫',
    'candy': '🍬',
    'lollipop': '🍭',
    'custard': '🍮',
    'honey_pot': '🍯',
    'baby_bottle': '🍼',
    'milk_glass': '🥛',
    'coffee': '☕',
    'tea': '🍵',
    'teapot': '🫖',
    'mate': '🧉',
    'bubble_tea': '🧋',
    'beverage_box': '🧃',
    'cup_with_straw': '🥤',
    'sake': '🍶',
    'beer': '🍺',
    'beers': '🍻',
    'champagne_glass': '🥂',
    'wine_glass': '🍷',
    'tumbler_glass': '🥃',
    'cocktail': '🍸',
    'tropical_drink': '🍹',
    'champagne': '🍾',
    'ice_cube': '🧊',
    'spoon': '🥄',
    'fork_and_knife': '🍴',
    'fork_and_knife_with_plate': '🍽️',
    'bowl_with_spoon2': '🥣',
    
    // Activities
    'soccer': '⚽',
    'basketball': '🏀',
    'football': '🏈',
    'baseball': '⚾',
    'softball': '🥎',
    'tennis': '🎾',
    'volleyball': '🏐',
    'rugby_football': '🏉',
    'flying_disc': '🥏',
    'boomerang': '🪃',
    '8ball': '🎱',
    'yo_yo': '🪀',
    'ping_pong': '🏓',
    'badminton': '🏸',
    'hockey': '🏒',
    'field_hockey': '🏑',
    'lacrosse': '🥍',
    'cricket_game': '🏏',
    'goal_net': '🥅',
    'golf': '⛳',
    'kite': '🪁',
    'bow_and_arrow': '🏹',
    'fishing_pole_and_fish': '🎣',
    'diving_mask': '🤿',
    'boxing_glove': '🥊',
    'martial_arts_uniform': '🥋',
    'running_shirt_with_sash': '🎽',
    'skateboard': '🛹',
    'roller_skate': '🛼',
    'sled': '🛷',
    'ice_skate': '⛸️',
    'curling_stone': '🥌',
    'ski': '🎿',
    'skier': '⛷️',
    'snowboarder': '🏂',
    'parachute': '🪂',
    'person_lifting_weights': '🏋️',
    'woman_lifting_weights': '🏋️‍♀️',
    'man_lifting_weights': '🏋️‍♂️',
    'people_wrestling': '🤼',
    'women_wrestling': '🤼‍♀️',
    'men_wrestling': '🤼‍♂️',
    'person_doing_cartwheel': '🤸',
    'woman_cartwheeling': '🤸‍♀️',
    'man_cartwheeling': '🤸‍♂️',
    'person_bouncing_ball': '⛹️',
    'woman_bouncing_ball': '⛹️‍♀️',
    'man_bouncing_ball': '⛹️‍♂️',
    'person_fencing': '🤺',
    'person_playing_handball': '🤾',
    'woman_playing_handball': '🤾‍♀️',
    'man_playing_handball': '🤾‍♂️',
    'person_golfing': '🏌️',
    'woman_golfing': '🏌️‍♀️',
    'man_golfing': '🏌️‍♂️',
    'horse_racing': '🏇',
    'person_in_lotus_position': '🧘',
    'woman_in_lotus_position': '🧘‍♀️',
    'man_in_lotus_position': '🧘‍♂️',
    'person_surfing': '🏄',
    'woman_surfing': '🏄‍♀️',
    'man_surfing': '🏄‍♂️',
    'person_swimming': '🏊',
    'woman_swimming': '🏊‍♀️',
    'man_swimming': '🏊‍♂️',
    'person_playing_water_polo': '🤽',
    'woman_playing_water_polo': '🤽‍♀️',
    'man_playing_water_polo': '🤽‍♂️',
    'person_rowing_boat': '🚣',
    'woman_rowing_boat': '🚣‍♀️',
    'man_rowing_boat': '🚣‍♂️',
    
    // Travel & Places
    'red_car': '🚗',
    'taxi': '🚕',
    'blue_car': '🚙',
    'pickup_truck': '🛻',
    'minibus': '🚐',
    'bus': '🚌',
    'trolleybus': '🚎',
    'race_car': '🏎️',
    'police_car': '🚓',
    'ambulance': '🚑',
    'fire_engine': '🚒',
    'truck': '🚚',
    'articulated_lorry': '🚛',
    'tractor': '🚜',
    'white_check_mark': '✅',
    'ballot_box_with_check': '☑️',
    'heavy_check_mark': '✔️',
    'x': '❌',
    'negative_squared_cross_mark': '❎',
    'heavy_multiplication_x': '✖️',
    'heavy_plus_sign': '➕',
    'heavy_minus_sign': '➖',
    'heavy_division_sign': '➗',
    'curly_loop': '➰',
    'loop': '➿',
    'part_alternation_mark': '〽️',
    'eight_spoked_asterisk': '✳️',
    'eight_pointed_black_star': '✴️',
    'sparkle': '❇️',
    'bangbang': '‼️',
    'interrobang': '⁉️',
    'question': '❓',
    'grey_question': '❔',
    'grey_exclamation': '❕',
    'exclamation': '❗',
    'heavy_exclamation_mark': '❗',
    'wavy_dash': '〰️',
    'copyright': '©️',
    'registered': '®️',
    'tm': '™️',
    'hash': '#️⃣',
    'asterisk': '*️⃣',
    'zero': '0️⃣',
    'one': '1️⃣',
    'two': '2️⃣',
    'three': '3️⃣',
    'four': '4️⃣',
    'five': '5️⃣',
    'six': '6️⃣',
    'seven': '7️⃣',
    'eight': '8️⃣',
    'nine': '9️⃣',
    'keycap_ten': '🔟',
    
    // Symbols
    'warning': '⚠️',
    'children_crossing': '🚸',
    'beginner': '🔰',
    'u6307': '🈯',
    'chart': '💹',
    'sparkles': '✨',
    'fire': '🔥',
    'tada': '🎉',
    'party_popper': '🎉',
    'confetti_ball': '🎊',
    'crossed_flags': '🎌',
    'pine_decoration': '🎍',
    'japanese_castle': '🏯',
    'european_castle': '🏰',
    'tokyo_tower': '🗼',
    'statue_of_liberty': '🗽',
    'japan': '🗾',
    'moyai': '🗿',
    'grinning_face_with_star_eyes': '🤩',
    'grinning_face_with_one_large_and_one_small_eye': '🤪',
    'sign_of_the_horns': '🤘',
    'call_me': '🤙',
    'left-facing_fist': '🤛',
    'right-facing_fist': '🤜',
    'i_love_you_hand_sign': '🤟',
    'face_with_cowboy_hat': '🤠',
    'clown_face': '🤡',
    'rolling_on_the_floor_laughing': '🤣',
    'star_struck2': '🤩',
    'zany_face2': '🤪',
    'face_with_symbols_on_mouth': '🤬',
    'face_vomiting2': '🤮',
    'exploding_head2': '🤯',
    'pregnant_woman': '🤰',
    'breast-feeding': '🤱',
    'selfie2': '🤳',
    'prince': '🤴',
    'man_in_tuxedo': '🤵',
    'mrs_claus': '🤶',
    'shrug': '🤷',
    'person_doing_cartwheel2': '🤸',
    'juggling': '🤹',
    'fencer': '🤺',
    'wrestlers': '🤼',
    'water_polo': '🤽',
    'handball': '🤾',
    'diving_mask2': '🤿',
    'wilted_flower2': '🥀',
    'drum_with_drumsticks': '🥁',
    'clinking_glasses': '🥂',
    'tumbler_glass2': '🥃',
    'spoon2': '🥄',
    'goal_net2': '🥅',
    'first_place_medal': '🥇',
    'second_place_medal': '🥈',
    'third_place_medal': '🥉',
    'boxing_glove2': '🥊',
    'martial_arts_uniform2': '🥋',
    'curling_stone2': '🥌',
    'lacrosse2': '🥍',
    'softball2': '🥎',
    'flying_disc2': '🥏',
    'croissant2': '🥐',
    'avocado2': '🥑',
    'cucumber2': '🥒',
    'bacon2': '🥓',
    'carrot2': '🥕',
    'baguette_bread2': '🥖',
    'green_salad2': '🥗',
    'shallow_pan_of_food2': '🥘',
    'stuffed_flatbread2': '🥙',
    'egg2': '🥚',
    'glass_of_milk': '🥛',
    'peanuts2': '🥜',
    'kiwifruit': '🥝',
    'pancakes2': '🥞',
    'dumpling2': '🥟',
    'fortune_cookie2': '🥠',
    'takeout_box2': '🥡',
    'chopsticks': '🥢',
    'bowl_with_spoon3': '🥣',
    'cup_with_straw2': '🥤',
    'coconut2': '🥥',
    'broccoli2': '🥦',
    'pie2': '🥧',
    'pretzel2': '🥨',
    'cut_of_meat2': '🥩',
    'sandwich2': '🥪',
    'canned_food2': '🥫',
    'leafy_green2': '🥬',
    'mango2': '🥭',
    'moon_cake2': '🥮',
    'bagel2': '🥯',
    'smiling_face_with_hearts2': '🥰',
    'yawning_face': '🥱',
    'smiling_face_with_tear': '🥲',
    'partying_face2': '🥳',
    'woozy_face2': '🥴',
    'hot_face2': '🥵',
    'cold_face2': '🥶',
    'ninja': '🥷',
    'disguised_face2': '🥸',
    'face_in_clouds2': '😶‍🌫️',
    'face_exhaling2': '😮‍💨',
    'heart_on_fire2': '❤️‍🔥',
    'mending_heart2': '❤️‍🩹',
    'man_with_veil': '👰‍♂️',
    'woman_with_veil': '👰‍♀️',
    'woman_feeding_baby': '👩‍🍼',
    'man_feeding_baby': '👨‍🍼',
    'person_feeding_baby': '🧑‍🍼',
    'mx_claus': '🧑‍🎄',
    'people_hugging': '🫂',
    'black_cat2': '🐈‍⬛',
    'bison2': '🦬',
    'mammoth2': '🦣',
    'beaver2': '🦫',
    'polar_bear': '🐻‍❄️',
    'dodo2': '🦤',
    'feather': '🪶',
    'seal': '🦭',
    'cockroach': '🪳',
    'fly': '🪰',
    'worm2': '🪱',
    'beetle': '🪲',
    'lotus2': '🪷',
    'potted_plant': '🪴',
    ' blueberries': '🫐',
    'olive2': '🫒',
    'bell_pepper2': '🫑',
    'flatbread2': '🫓',
    'tamale2': '🫔',
    'fondue2': '🫕',
    'teapot2': '🫖',
    'bubble_tea2': '🧋',
    'beverage_box2': '🧃',
    'mate2': '🧉',
    'ice2': '🧊',
    'pickup_truck2': '🛻',
    'roller_skate2': '🛼',
    'magic_wand': '🪄',
    'piñata': '🪅',
    'nesting_dolls': '🪆',
    'sewing_needle': '🪡',
    'knot': '🪢',
    'mirror': '🪞',
    'window': '🪟',
    'plunger': '🪠',
    'seal2': '🦭',
    'fly2': '🪰',
    'cockroach2': '🪳',
    'potted_plant2': '🪴',
    'wood': '🪵',
    'hut': '🛖',
    'elevator': '🛗',
    'manual_wheelchair': '🦽',
    'motorized_wheelchair': '🦼',
    'auto_rickshaw': '🛺',
    'parachute2': '🪂',
    'ringed_planet': '🪐',
    'chair': '🪑',
    'razor': '🪒',
    'axe': '🪓',
    'diya_lamp': '🪔',
    'banjo': '🪕',
    'military_helmet': '🪖',
    'accordion': '🪗',
    'long_drum': '🪘',
    'coin': '🪙',
    'boomerang2': '🪃',
}

const preferredEmojiNames: Record<string, string> = {
    '👍': '+1',
    '👎': '-1',
    '❤️': 'heart',
    '😄': 'smile',
    '😃': 'smiley',
    '😀': 'grinning',
    '😆': 'laughing',
}

const emojiNameByChar = Object.entries(emojiMap).reduce<Record<string, string>>((acc, [name, char]) => {
    if (!acc[char]) {
        acc[char] = preferredEmojiNames[char] || name
    }
    return acc
}, {})

/**
 * Search emojis by query string
 * Returns array of {name, char} matching the query
 */
export function searchEmojis(query: string, limit: number = 8): Array<{ name: string; char: string }> {
    const cleanQuery = query.toLowerCase().replace(/^:|:$/g, '')
    if (!cleanQuery) return []
    
    const results: Array<{ name: string; char: string; score: number }> = []
    
    for (const [name, char] of Object.entries(emojiMap)) {
        const lowerName = name.toLowerCase()
        let score = 0
        
        // Exact match
        if (lowerName === cleanQuery) {
            score = 100
        }
        // Starts with query
        else if (lowerName.startsWith(cleanQuery)) {
            score = 50
        }
        // Contains query
        else if (lowerName.includes(cleanQuery)) {
            score = 25
        }
        // Query contains name (partial match)
        else if (cleanQuery.includes(lowerName)) {
            score = 10
        }
        
        if (score > 0) {
            results.push({ name, char, score })
        }
    }
    
    // Sort by score descending
    results.sort((a, b) => b.score - a.score)
    
    // Return top matches
    return results.slice(0, limit).map(({ name, char }) => ({ name, char }))
}

/**
 * Gets the Unicode character for a given emoji name.
 * Returns the original name if no match is found.
 */
export function getEmojiChar(name: string): string {
    // Strip colons if present: ":heart:" -> "heart"
    const cleanName = name.replace(/^:|:$/g, '').toLowerCase();
    return emojiMap[cleanName] || name;
}

/**
 * Returns a stable key for reaction comparisons.
 * Known aliases normalize to the same rendered emoji so ":+1:", "thumbsup", and "👍" collapse together.
 */
export function getReactionEmojiKey(value: string): string {
    const cleanValue = value.replace(/^:|:$/g, '').trim()
    if (!cleanValue) {
        return value
    }

    const lowerValue = cleanValue.toLowerCase()
    return emojiMap[lowerValue] || cleanValue
}

/**
 * Returns the preferred API name for an emoji.
 * Keeps server requests consistent even when the UI is using rendered glyphs.
 */
export function getPreferredEmojiName(value: string): string {
    const cleanValue = value.replace(/^:|:$/g, '').trim()
    if (!cleanValue) {
        return value
    }

    const lowerValue = cleanValue.toLowerCase()
    if (emojiMap[lowerValue]) {
        return preferredEmojiNames[emojiMap[lowerValue]] || lowerValue
    }

    return emojiNameByChar[cleanValue] || cleanValue
}

/**
 * Replaces all :emoji_name: patterns in a string with Unicode characters.
 */
export function replaceEmojiNames(text: string): string {
    return text.replace(/:([a-z0-9_+-]+):/g, (match, name) => {
        const char = emojiMap[name.toLowerCase()];
        return char || match;
    });
}
